### ISSUE TITLE
Instant Lama Cleaner crash on newest SD version.

### ISSUE THREAD

**Issue by ArchAngelAries** [aka7774/sd_lama_cleaner#1]
Still works on older version of SD but on the latest SD the command window throws errors and instantly closes before I can read the error. Please update if possible, this tool is so useful as an extension.

**Comment by aka7774** [comment]
I've received similar reports, but I'm busy right now, so I'll look at it after Tuesday.

**Comment by ArchAngelAries** [comment]
> I've received similar reports, but I'm busy right now, so I'll look at it after Tuesday.

Understood. I appreciate all your hard work. Thank you for making this. I'd contribute if I had any coding skills but my knowledge about coding is extremely novice.

**Comment by ArchAngelAries** [comment]
Running into a new error on Windows with the latest update on your extension:

  File "D:\AI\stable-diffusion-webui\launch.py", line 97, in run
    raise RuntimeError(message)
RuntimeError: Error running command.
Command: start venv/bin/lama-cleaner --model=lama --device=cpu --port=7870
Error code: 1
stdout: <empty>
stderr: The system cannot find the file venv/bin/lama-cleaner.

**Comment by aka7774** [comment]
Sorry, Maybe it works, but I haven't tested it.
I'm moving and can't use windows!

**Comment by aka7774** [comment]
maybe done.
