### ISSUE TITLE
FinalizeS3 was not called even though S3 was initialized.  This could lead to a segmentation fault at exit

### ISSUE THREAD

**Issue by makisekurisu-jp** [aka7774/sd_lama_cleaner#3]
`C:\arrow\cpp\src\arrow\filesystem\s3fs.cc:2829:  arrow::fs::FinalizeS3 was not called even though S3 was initialized.  This could lead to a segmentation fault at exit`

Restart webui shows this error.If uninstall this extension, webui can restart normally.

![20231003165419](https://github.com/aka7774/sd_lama_cleaner/assets/72290820/44ffa66f-5984-4431-ac1b-95cb3d7f33b1)

![20231003165352](https://github.com/aka7774/sd_lama_cleaner/assets/72290820/972913aa-42c5-4fde-9fa6-2a21d18b4d7d)

![20231003165439](https://github.com/aka7774/sd_lama_cleaner/assets/72290820/76dfcfce-236e-4df3-ab8c-aec6afc2744f)

**Comment by aka7774** [comment]
It worked fine here.
It may be a problem on the lama-cleaner side during installation.
Please try manual installation.

```bash
cd stable-diffusion-webui
venv/Scripts/pip install -U lama-cleaner
```

for Linux:
```bash
venv/bin/pip install -U lama-cleaner
```

**Comment by makisekurisu-jp** [comment]
I didn't continue to test, because this extension will make apply and restart ui not work. So I installed the original project of lama-cleaner.

**Comment by aka7774** [comment]
Thanks for the report.
I am not using Amazon S3 for this extension and I don't think it has anything to do with this issue.
